[build]
  publish = "src"
  command = "# no build command needed"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Override for API endpoints (if you implement serverless functions later)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
